html!: handle misleading '>' in tag attributes
### Problem
The html! macro didn't handle cases like this one:

```rust
html! {
    <div onclick=|_| 2 > 1 />
    //                 ^ this
}
```

Moreover, the introduction of handling of mixed self-closing and not
self-closing tags introduced a buggy error message, which is now fixed.

### Solution
The parser only allows '<', '{' or nothing after a tag's closing '>'.

`verify_end` is removed, and the presence of a closing tag is checked
when parsing the children.

Note: I also moved some tests around.

### Regression
Unfortunately, this change has a regression: the error message is less
good now, like here in `html-tag-fail.stderr`:

```
diff --git a/tests/macro/html-tag-fail.stderr b/tests/macro/html-tag-fail.stderr
index b14fc14..d59e8f4 100644
--- a/tests/macro/html-tag-fail.stderr
+++ b/tests/macro/html-tag-fail.stderr
@@ -52,11 +52,13 @@ error: only one root html element allowed
 12 |     html! { <img /></img> };
    |                    ^^^^^^

-error: expected valid html element
-  --> $DIR/html-tag-fail.rs:13:18
+error: unexpected end of input, expected token tree
+  --> $DIR/html-tag-fail.rs:13:5
    |
 13 |     html! { <div>Invalid</div> };
-   |                  ^^^^^^^
+   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
+   |
+   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

 error: only one `attr` attribute allowed
   --> $DIR/html-tag-fail.rs:15:27
```